INSERT INTO library.books (name, genre, year, author_id) VALUES ('Radunica', 'poetry', 1921, 1);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('The Tale of the Fisherman and the Fish', 'Fairy tale', 1833, 2);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('Fahrenheit 451', 'science fiction', 1953, 3);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('A journey to the center of the earth', 'science fiction', 1864, 4);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('All summer in a day', 'science fiction', 1954, 3);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('Pugachev', 'poetry', 1922, 1);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('Na rosstaniah', 'novel', 1955, 5);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('Dubrovsky', 'novel', 1833, 2);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('Around the world in 80 Days', 'adventure novel', 1872, 4);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('Romeo and Juliet', 'poetry', 1597, 6);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('Hamlet', 'poetry', 1604, 6);
INSERT INTO library.books (name, genre, year, author_id) VALUES ('Golas ziamli', 'poetry', 1943, 5);